name: Build and Test Executable

on: [push, pull_request]

jobs:
  e2e-and-scan:
    name: E2E Tests & Defender Scan in Fresh VM
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Download build artifact
        run: |
          $artifact = Invoke-WebRequest -Uri https://github.com/lucaelin/Elite-Dangerous-AI-Integration/actions/runs/12917999396/artifacts/2471168679 -OutFile artifact.zip
          Expand-Archive -Path artifact.zip -Destination dist

      - name: List contents (debug)
        run: dir dist\AIGUI

      - name: Configure Windows Defender
        run: |
          Remove-MpPreference -ExclusionPath (Get-MpPreference).ExclusionPath
        shell: powershell

      - name: Update Defender signatures
        # Failed with hr = 0x80070002 means that a virus was detected (which is a bit counterintuitive)
        run: |
          "C:\Program Files\Windows Defender\MpCmdRun.exe" -SignatureUpdate
          "C:\Program Files\Windows Defender\MpCmdRun.exe" -Scan -ScanType 3 -File $PWD
        shell: cmd

      - name: Output scan results
        # This is an additional step to check the MpThreatDetection, which in our tests did not work, but it's worth a try
        run: |
          Get-Content $env:TEMP\MpCmdRun.log
          Get-MpThreatDetection
          $count = (Get-MpThreatDetection).Count

          exit $count

      - name: Run e2e tests
        run: |
          python --version
          python e2e/test_ChatExecutable.py
