name: Build and Test Executable

on: [push, pull_request]

jobs:
  e2e-and-scan:
    name: E2E Tests & Defender Scan in Fresh VM
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Download build artifact
        run: |
          $artifact = Invoke-WebRequest -Uri https://github.com/RatherRude/Elite-Dangerous-AI-Integration/releases/download/v1.8.3/COVAS_NEXT_v1_8_3.zip -OutFile artifact.zip
          Expand-Archive -Path artifact.zip -Destination dist

      - name: List contents (debug)
        run: dir dist\AIGUI

      - name: Install PsTools
        run: |
          Invoke-WebRequest -Uri https://download.sysinternals.com/files/PSTools.zip -OutFile pstools.zip
          Expand-Archive -Path pstools.zip -Destination pstools
          $env:PATH += ";$PWD\pstools"
          echo $env:PATH
          dir $PWD\pstools

      - name: Configure Windows Defender
        run: |
          Remove-MpPreference -ExclusionPath (Get-MpPreference).ExclusionPath
        shell: powershell

      - name: Run MpCmdRun as SYSTEM in cmd using PsExec
        run: |
          D:\a\Elite-Dangerous-AI-Integration\Elite-Dangerous-AI-Integration\pstools\PsExec.exe -accepteula /dis cmd.exe /k """C:\Program Files\Windows Defender\MpCmdRun.exe"" -Scan -ScanType 3 -File ""$PWD\dist\AIGUI\AIGUI.exe"" > C:\out.txt & echo Done > C:\done.txt & exit"  || & { "ignore failure"; $global:LASTEXITCODE = 0 }
          echo "MpCmdRun Started"
          while (-not (Test-Path C:\done.txt)) { Start-Sleep -Seconds 1 }
          echo "MpCmdRun Finished"
          Start-Sleep -Seconds 5

      - name: Output scan results
        # This is an additional step to check the MpThreatDetection, which in our tests did not work, but it's worth a try
        run: |
          Get-Content C:\out.txt
          Get-MpThreatDetection
          $count = (Get-MpThreatDetection).Count

          exit $count

      - name: Run e2e tests
        run: |
          python --version
          python e2e/test_ChatExecutable.py
