name: Build and Test Executable

on: [push, pull_request]

jobs:
  e2e-and-scan:
    name: E2E Tests & Defender Scan in Fresh VM
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Download build artifact
        run: |
          $artifact = Invoke-WebRequest -Uri https://github.com/RatherRude/Elite-Dangerous-AI-Integration/releases/download/v1.8.3/COVAS_NEXT_v1_8_3.zip -OutFile artifact.zip
          Expand-Archive -Path artifact.zip -Destination dist

      - name: List contents (debug)
        run: dir dist\AIGUI

      - run: |
          $fileName = $PWD\dist\AIGUI\AIGUI.exe
          Remove-MpPreference -ExclusionPath (Get-MpPreference).ExclusionPath
          $taskName = "FileScan"
          schtasks /create /tn $taskName /sc DAILY /st 13:00 /ru SYSTEM /rl HIGHEST /tr "'C:\Program Files\Windows Defender\MpCmdRun.exe' -Scan -ScanType 3 -File $fileName"
          Start-ScheduledTask -TaskName $taskName
          while ((Get-ScheduledTask -TaskName $taskName).State  -ne 'Ready') 
          {
              Start-Sleep -Seconds 5
          }
          Get-MpThreatDetection

      - name: Output scan results
        # This is an additional step to check the MpThreatDetection, which in our tests did not work, but it's worth a try
        run: |
          Get-Content $env:TEMP\MpCmdRun.log
          Get-MpThreatDetection
          $count = (Get-MpThreatDetection).Count

          exit $count

      - name: Run e2e tests
        run: |
          python --version
          python e2e/test_ChatExecutable.py
